worker_processes auto;
events { worker_connections 1024; }

http {
  include       /etc/nginx/mime.types;
  default_type  application/octet-stream;
  sendfile      on;
  keepalive_timeout 65;

  upstream frontend_upstream { server frontend:8080; }
  upstream user_upstream { server user:8080; }
  upstream auth_upstream { server auth:8080; }
  upstream catalog_upstream { server catalog:8080; }
  upstream cart_upstream { server cart:8080; }
  upstream order_upstream { server order:8080; }
  upstream payment_upstream { server payment:8080; }

  server {
    listen 8080;

    # Frontend
    location / {
      proxy_pass http://frontend_upstream;
      proxy_set_header Host $host;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header X-Forwarded-Proto $scheme;
    }

    # APIs
    location /api/users/ {
      proxy_pass http://user_upstream/;
    }
    location /api/auth/ {
      proxy_pass http://auth_upstream/;
    }
    location /api/catalog/ {
      proxy_pass http://catalog_upstream/;
    }
    location /api/cart/ {
      proxy_pass http://cart_upstream/;
    }
    location /api/order/ {
      proxy_pass http://order_upstream/;
    }
    location /api/payment/ {
      proxy_pass http://payment_upstream/;
    }
  }
}

